services:
  - type: web
    name: devtracker-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://devtracker:fTmtDWCyjPhaQU81yCctwQMXsQJS9eHd@dpg-da8taoqjnfac73c0r1q0-a/devtracker_woxn?sslmode=require
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_TTL
        value: 15m
      - key: JWT_REFRESH_TTL_DAYS
        value: 30
      - key: CORS_ORIGIN
        value: https://devtracker.onrender.com
      - key: FRONTEND_URL
        value: https://devtracker.onrender.com
      - key: API_URL
        value: https://devtracker-backed.onrender.com
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM
        value: DevTracker <onboarding@resend.dev>
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: FACEBOOK_CLIENT_ID
        sync: false
      - key: FACEBOOK_CLIENT_SECRET
        sync: false
